version: '3.1'
services:
  scheduler:
    # When running locally, we want to mount the dbt directory into the scheduler container
    # at <relative-project-path>:<mount-path>
    volumes:
      - ../dbt:/usr/local/airflow/dbt
