name: Astronomer CI - Deploy Airflow and dbt code
on:
  push:
    branches:
      - main

jobs:
  prod-astronomer:
    env:
      ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN }}
      DEPLOYMENT_ID: ${{ vars.DEPLOYMENT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_ACTIONS env var
        run: echo "GITHUB_ACTIONS=${GITHUB_ACTIONS}"
      - name: DBT Deploy Bigquery
        uses: astronomer/deploy-action@main
        with:
          deploy-type: dbt
          deployment-id: ${{ vars.DEPLOYMENT_ID }}
          root-folder: dbt/postgres/
          mount-path: /usr/local/airflow/dbt/postgres
      - name: DBT Deploy Databricks
        uses: astronomer/deploy-action@main
        with:
          action: deploy
          deploy-type: dbt
          deployment-id: ${{ vars.DEPLOYMENT_ID }}
          root-folder: dbt/databricks/
          mount-path: /usr/local/airflow/dbt/databricks
      - name: Deploy DAGs/Image
        uses: astronomer/deploy-action@main
        with:
          action: deploy
          deploy-type: infer
          root-folder: astro_cosmos_project
          deployment-id: ${{ vars.DEPLOYMENT_ID }}
